### ISSUE TITLE
Working example for GW170817 PE with IMRPhenomD

### ISSUE THREAD

**Issue by ThibeauWouters** [kazewong/jim#38]
Dear,

Peter Pang and I are currently exploring the use of jim to perform parameter estimation on BNS events, for which we wish to use the TaylorF2 waveform model that we have currently implemented in ripple and will push to the main ripple repository once we have cleaned up the code and finalized all checks against the lalsuite implementation. In order to be able to make full use of jim, we are kindly requesting to have a fully working and updated example that shows how to analyze GW170817 with jim with the IMRPhenomD waveform, in order to reproduce the PE reported in the jim paper. We have been trying to get a good run set up but have been struggling with adapting the hyperparameters starting from the provided GW150914 run to get satisfactory results for GW170817 that agree with the results from Bilby or those mentioned in the paper. 

Thanks in advance for any help provided!

**Comment by kazewong** [comment]
This is addressed in #49 . Closing the issue now
