### ISSUE TITLE
Adding generic transformation function

### ISSUE THREAD

**Issue by tsunhopang** [kazewong/jim#83]
It would be good to have a more generic transformation function/interface than the currently available  1-to-1 mapping function in `jim`.

That would be particularly useful for nuclear equation-of-state study, in which one would need to sample over the masses (2 parameters) and the EOS parameters (1 to N), then transform them into the tidal deformabilities (2 parameters) by solving the TOV equations.

**Comment by kazewong** [comment]
So currently the prior and transforms are lumped together, which I think to some extent limits the flexibility in composing transforms and priors. Perhaps we should revisit this idea and separate the transforms from priors

**Comment by ThibeauWouters** [comment]
I implemented something like this to handle sampling over the Hubble constant and the redshift, from which the luminosity distance is computed and then fed into the likelihood. You can find the code in [this branch](https://github.com/ThibeauWouters/jim/commit/bece23bf2bf28f694d1d145495a51e1bb382beaf) (note: this is with an older version of jim). An example notebook showing how to use the code is [here](https://github.com/ThibeauWouters/jim_H0/blob/v2/v2/explore.ipynb)

However, in this implementation, we need to explicitly tell which keys we just want to copy over and not transform, which is annoying and still needs to be fixed.

**Comment by kazewong** [comment]
Closed by release `v0.2.0`
