### ISSUE TITLE
SingleEventRun requires path for injection

### ISSUE THREAD

**Issue by thomasckng** [kazewong/jim#92]
SingleEventRun requires path for injection, which is not necessary.

**Comment by kazewong** [comment]
Do you mean the instantiation of path here in the run is not necessary? https://github.com/kazewong/jim/blob/94c34db26783f4b8d3e032ba75e2ed9fea9b578f/src/jimgw/single_event/runManager.py#L68

**Comment by thomasckng** [comment]
For injection, the path is not used anywhere I think.

**Comment by thomasckng** [comment]
Solved with #103.
